"""Data models for the content generation workflow.

This subpackage replaces the former monolithic ``content_gen/models.py``.
All public models are re-exported here for backward compatibility.

Contract Version: 1.8.0
"""

from __future__ import annotations

# Stage-specific models
from .angle import (
    AngleDefinition,
    AngleOption,
    AngleOutput,
    BeatIntent,
    BeatIntentMap,
    CoreInputs,
    CtAVariants,
    DerivativeOpportunity,
    EarlyPackagingSignals,
    HookSet,
    StrategyMemory,
    ThesisArtifact,
)
from .backlog import (
    AudienceProblemFitFields,
    BacklogItem,
    BacklogOutput,
    ContentExecutionFields,
    IdeaCoreFields,
    IdeaScores,
    PipelineCandidate,
    PrioritizationFields,
    ScoringOutput,
    TriageOperation,
    TriageResponse,
    ValidationLayerFields,
)
from .brief import (
    BriefExecutionGate,
    BriefRevision,
    ManagedBriefOutput,
    ManagedOpportunityBrief,
    OpportunityBrief,
    PipelineBriefReference,
    StrategyReadinessIssue,
    StrategyReadinessResult,
)

# Contracts
from .contracts import (
    CONTENT_GEN_STAGE_CONTRACTS,
    CONTRACT_VERSION,
    ContentGenStageContract,
)
from .learning import (
    ContentGenRunMetrics,
    OperatingFitnessMetrics,
    PerformanceAnalysis,
    PerformanceLearning,
    PerformanceLearningSet,
    PlanningLearning,
    PlanningMetrics,
    RuleVersion,
    RuleVersionHistory,
    StrategyPerformanceGuidance,
)
from .pipeline import (
    DEFAULT_PHASE_POLICIES,
    OPERATING_PHASE_LABELS,
    PHASE_TO_STAGES_MAPPING,
    PIPELINE_STAGE_LABELS,
    PIPELINE_STAGES,
    STAGE_TO_PHASE_MAPPING,
    OperatingPhasePolicy,
    PhaseExitCriteria,
    PhaseKillCondition,
    PhaseReuseOpportunity,
    PhaseSkipCondition,
    PipelineContext,
    PipelineLaneContext,
    PipelineStageTrace,
    StageTraceMetadata,
    get_phase_for_stage,
    get_phase_policy,
    get_stages_for_phase,
)
from .production import (
    CONTENT_TYPE_PROFILES,
    AssetFallback,
    BeatRevisionScope,
    BeatVisual,
    ContentTypeProfile,
    HumanQCGate,
    IterationState,
    MissingAssetDecision,
    PackagingOutput,
    PlatformPackage,
    ProductionBrief,
    PublishItem,
    QualityEvaluation,
    RunConstraints,
    TargetedRevisionPlan,
    TargetedRewriteAction,
    VisualPlanOutput,
    VisualProductionExecutionBrief,
    get_content_type_profile,
)
from .research import (
    ClaimTraceEntry,
    ClaimTraceLedger,
    FactRiskGate,
    FactRiskGateOutput,
    FactRiskGateResult,
    ProgressiveQCCheckpoint,
    ProgressiveQCIssue,
    ResearchClaim,
    ResearchCounterpoint,
    ResearchDepthRouting,
    ResearchFinding,
    ResearchPack,
    ResearchSource,
    ResearchUncertaintyFlag,
    RetrievalBudget,
    RetrievalDecision,
    RetrievalPlan,
    ScriptClaimStatement,
)
from .script import (
    ArgumentBeatClaim,
    ArgumentClaim,
    ArgumentCounterargument,
    ArgumentMap,
    ArgumentProofAnchor,
    BeatIntent,
    BeatIntentMap,
    CtAVariants,
    HookSet,
    QCCheck,
    QCResult,
    SavedScriptRun,
    ScriptingContext,
    ScriptingIterations,
    ScriptingIterationSummary,
    ScriptingLLMCallTrace,
    ScriptingRunResult,
    ScriptingStepTrace,
    ScriptStructure,
    ScriptVersion,
    VisualNote,
)

# Aliases for backward compatibility
CtaVariants = CtAVariants

# Shared enums and types
from .shared import (
    BriefExecutionPolicyMode,
    BriefLifecycleState,
    BriefProvenance,
    ClaimStatus,
    ClaimTraceStage,
    ClaimTraceStatus,
    DraftLaneDecision,
    EffortTier,
    EvidenceDirectness,
    FactRiskDecision,
    LearningCategory,
    LearningDurability,
    MissingAssetDecision,
    OperatingPhase,
    PlanningLearningCategory,
    ProductionComplexity,
    ReleaseState,
    ResearchClaimType,
    ResearchConfidence,
    ResearchDepthTier,
    ResearchFindingType,
    ResearchFlagType,
    ResearchSeverity,
    RetrievalMode,
    RevisionMode,
    RewriteActionType,
    RuleChangeOperation,
    RuleLifecycleStatus,
    RuleVersionKind,
    SourceAuthority,
    SourceFreshness,
    StrategyReadiness,
    TriageOperationKind,
    VisualComplexity,
)

# ─────────────────────────────────────────────────────────────────────────────
# Legacy constants and helpers that lived in models.py
# ─────────────────────────────────────────────────────────────────────────────

SCRIPTING_STEPS: list[str] = [
    "define_core_inputs",
    "define_angle",
    "choose_structure",
    "define_beat_intents",
    "generate_hooks",
    "draft_script",
    "add_retention_mechanics",
    "tighten",
    "add_visual_notes",
    "run_qc",
]

SCRIPTING_STEP_LABELS: dict[str, str] = {
    "define_core_inputs": "Defining core inputs",
    "define_angle": "Defining angle",
    "choose_structure": "Choosing structure",
    "define_beat_intents": "Defining beat intents",
    "generate_hooks": "Generating hooks",
    "draft_script": "Drafting script",
    "add_retention_mechanics": "Adding retention mechanics",
    "tighten": "Tightening script",
    "add_visual_notes": "Adding visual notes",
    "run_qc": "Running QC",
}


__all__ = [
    # Shared
    "ClaimStatus",
    "ClaimTraceStage",
    "ClaimTraceStatus",
    "DraftLaneDecision",
    "EffortTier",
    "EvidenceDirectness",
    "FactRiskDecision",
    "LearningCategory",
    "LearningDurability",
    "MissingAssetDecision",
    "OperatingPhase",
    "PlanningLearningCategory",
    "ProductionComplexity",
    "ReleaseState",
    "ResearchClaimType",
    "ResearchConfidence",
    "ResearchDepthTier",
    "ResearchFindingType",
    "ResearchFlagType",
    "ResearchSeverity",
    "RetrievalMode",
    "RevisionMode",
    "RewriteActionType",
    "RuleChangeOperation",
    "RuleLifecycleStatus",
    "RuleVersionKind",
    "SourceAuthority",
    "SourceFreshness",
    "StrategyReadiness",
    "TriageOperationKind",
    "VisualComplexity",
    "BriefExecutionPolicyMode",
    "BriefLifecycleState",
    "BriefProvenance",
    # Contracts
    "CONTRACT_VERSION",
    "CONTENT_GEN_STAGE_CONTRACTS",
    "ContentGenStageContract",
    # Angle
    "AngleDefinition",
    "AngleOption",
    "AngleOutput",
    "BeatIntent",
    "BeatIntentMap",
    "CoreInputs",
    "CtAVariants",
    "DerivativeOpportunity",
    "EarlyPackagingSignals",
    "HookSet",
    "StrategyMemory",
    "ThesisArtifact",
    # Backlog
    "AudienceProblemFitFields",
    "BacklogItem",
    "BacklogOutput",
    "ContentExecutionFields",
    "IdeaCoreFields",
    "IdeaScores",
    "PipelineCandidate",
    "PrioritizationFields",
    "ScoringOutput",
    "TriageOperation",
    "TriageResponse",
    "ValidationLayerFields",
    # Brief
    "BriefExecutionGate",
    "BriefRevision",
    "ManagedBriefOutput",
    "ManagedOpportunityBrief",
    "OpportunityBrief",
    "PhaseExitCriteria",
    "PhaseKillCondition",
    "PhaseReuseOpportunity",
    "PhaseSkipCondition",
    "PipelineBriefReference",
    "StrategyReadinessIssue",
    "StrategyReadinessResult",
    # Learning
    "ContentGenRunMetrics",
    "OperatingFitnessMetrics",
    "PerformanceAnalysis",
    "PerformanceLearning",
    "PerformanceLearningSet",
    "PlanningLearning",
    "PlanningMetrics",
    "StrategyPerformanceGuidance",
    # Pipeline
    "DEFAULT_PHASE_POLICIES",
    "OPERATING_PHASE_LABELS",
    "PHASE_TO_STAGES_MAPPING",
    "PIPELINE_STAGE_LABELS",
    "PIPELINE_STAGES",
    "STAGE_TO_PHASE_MAPPING",
    "OperatingPhasePolicy",
    "PhaseExitCriteria",
    "PhaseKillCondition",
    "PhaseReuseOpportunity",
    "PhaseSkipCondition",
    "PipelineContext",
    "PipelineLaneContext",
    "PipelineStageTrace",
    "StageTraceMetadata",
    "get_phase_for_stage",
    "get_phase_policy",
    "get_stages_for_phase",
    # Production
    "AssetFallback",
    "BeatRevisionScope",
    "BeatVisual",
    "ContentTypeProfile",
    "CONTENT_TYPE_PROFILES",
    "HumanQCGate",
    "IterationState",
    "MissingAssetDecision",
    "PlatformPackage",
    "ProductionBrief",
    "PublishItem",
    "QualityEvaluation",
    "TargetedRevisionPlan",
    "TargetedRewriteAction",
    "VisualPlanOutput",
    "VisualProductionExecutionBrief",
    # Research
    "ClaimTraceEntry",
    "ClaimTraceLedger",
    "ClaimTraceStage",
    "ClaimTraceStatus",
    "FactRiskGate",
    "FactRiskGateOutput",
    "FactRiskGateResult",
    "ProgressiveQCIssue",
    "ProgressiveQCCheckpoint",
    "ResearchCounterpoint",
    "ResearchDepthRouting",
    "ResearchFinding",
    "ResearchPack",
    "ResearchSource",
    "ResearchUncertaintyFlag",
    "RetrievalBudget",
    "RetrievalDecision",
    "RetrievalPlan",
    "ScriptClaimStatement",
    # Script
    "BeatIntent",
    "BeatIntentMap",
    "CtAVariants",
    "HookSet",
    "QCResult",
    "QCCheck",
    "SavedScriptRun",
    "ScriptStructure",
    "ScriptVersion",
    "ScriptingContext",
    "ScriptingIterationSummary",
    "ScriptingIterations",
    "ScriptingLLMCallTrace",
    "ScriptingRunResult",
    "ScriptingStepTrace",
    "VisualNote",
    # Backward compat
    "get_content_type_profile",
    "SCRIPTING_STEPS",
    "SCRIPTING_STEP_LABELS",
]


# Rebuild models to resolve forward references after all models are loaded
# Import Literal at runtime to ensure it's available during model_rebuild
from typing import Literal  # noqa: E402

PipelineContext.model_rebuild()
ScriptingContext.model_rebuild()

# Rebuild PipelineBriefReference to resolve OpportunityBrief forward reference
from .brief import PipelineBriefReference

PipelineBriefReference.model_rebuild()
