"""Background maintenance workflows for backlog hygiene.

This module provides recurring AI-powered maintenance jobs that run
periodically to keep the backlog healthy without operator prompting.

Maintenance jobs are read-mostly: they generate proposals that are
surfaced to the operator for review, rather than mutating state directly.

Job Types
=========
1. stale_item_review   - Items not updated in N days are flagged for refresh or archival.
2. gap_summary         - Themes or categories with low coverage are flagged for new ideas.
3. duplicate_watchlist - Items with highly similar titles/ideas are flagged for deduping.
4. rescoring_recommend  - Items whose scores are stale (>30 days) are flagged for rescoring.

All jobs output MaintenanceProposal records that are surfaced in the
dashboard as review items. Mutations require explicit operator approval.

Scheduling
==========
Jobs are scheduled via a simple in-process scheduler (threading-based)
that fires on a configurable interval. The interval is set in
ContentGenConfig.maintenance_interval_hours (default: 24 hours).
"""

from __future__ import annotations

import logging
import threading
import traceback
from datetime import UTC, datetime, timedelta
from difflib import SequenceMatcher
from enum import StrEnum
from typing import TYPE_CHECKING, Any
from uuid import uuid4

import yaml

from cc_deep_research.content_gen.backlog_service import BacklogService
from cc_deep_research.content_gen.models import BacklogItem
from cc_deep_research.content_gen.storage._paths import resolve_content_gen_file_path
from cc_deep_research.content_gen.storage.audit_store import AuditActor, AuditEventType, AuditStore

if TYPE_CHECKING:
    from cc_deep_research.config import Config

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Maintenance job types
# ---------------------------------------------------------------------------


class MaintenanceJobType(StrEnum):
    """Types of recurring maintenance jobs."""

    STALE_ITEM_REVIEW = "stale_item_review"
    GAP_SUMMARY = "gap_summary"
    DUPLICATE_WATCHLIST = "duplicate_watchlist"
    RESCORING_RECOMMEND = "rescoring_recommend"


class MaintenanceProposalStatus(StrEnum):
    """Status of a maintenance proposal."""

    PENDING = "pending"  # Awaiting operator review
    APPROVED = "approved"  # Operator approved, ready to apply
    REJECTED = "rejected"  # Operator rejected
    APPLIED = "applied"  # Successfully applied
    EXPIRED = "expired"  # No longer relevant (item deleted, etc.)


class MaintenanceProposal:
    """A single maintenance proposal surfaced to the operator for review.

    Proposals are generated by maintenance jobs but require operator
    approval before any backlog mutation is applied.
    """

    def __init__(
        self,
        proposal_id: str = "",
        job_type: MaintenanceJobType | str = "",
        title: str = "",
        description: str = "",
        affected_idea_ids: list[str] | None = None,
        suggested_patch: dict[str, Any] | None = None,
        priority: int = 0,
        status: MaintenanceProposalStatus = MaintenanceProposalStatus.PENDING,
        created_at: str = "",
        reviewed_at: str = "",
        reviewed_by: str = "",
        outcome: str = "",
    ) -> None:
        self.proposal_id = proposal_id or f"mnt_{uuid4().hex[:10]}"
        self.job_type = MaintenanceJobType(job_type) if job_type and isinstance(job_type, str) else job_type
        self.title = title
        self.description = description
        self.affected_idea_ids = affected_idea_ids or []
        self.suggested_patch = suggested_patch or {}
        self.priority = priority
        self.status = status
        self.created_at = created_at or datetime.now(tz=UTC).isoformat()
        self.reviewed_at = reviewed_at
        self.reviewed_by = reviewed_by
        self.outcome = outcome

    def to_dict(self) -> dict[str, Any]:
        job_type_val = self.job_type.value if isinstance(self.job_type, MaintenanceJobType) else str(self.job_type or "")
        return {
            "proposal_id": self.proposal_id,
            "job_type": job_type_val,
            "title": self.title,
            "description": self.description,
            "affected_idea_ids": self.affected_idea_ids,
            "suggested_patch": self.suggested_patch,
            "priority": self.priority,
            "status": str(self.status.value),
            "created_at": self.created_at,
            "reviewed_at": self.reviewed_at,
            "reviewed_by": self.reviewed_by,
            "outcome": self.outcome,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> MaintenanceProposal:
        return cls(
            proposal_id=data.get("proposal_id", ""),
            job_type=data.get("job_type", ""),
            title=data.get("title", ""),
            description=data.get("description", ""),
            affected_idea_ids=data.get("affected_idea_ids", []),
            suggested_patch=data.get("suggested_patch", {}),
            priority=data.get("priority", 0),
            status=data.get("status", MaintenanceProposalStatus.PENDING),
            created_at=data.get("created_at", ""),
            reviewed_at=data.get("reviewed_at", ""),
            reviewed_by=data.get("reviewed_by", ""),
            outcome=data.get("outcome", ""),
        )


class MaintenanceRun:
    """Record of a single maintenance job execution."""

    def __init__(
        self,
        run_id: str = "",
        job_type: MaintenanceJobType | str = "",
        proposals_count: int = 0,
        started_at: str = "",
        completed_at: str = "",
        outcome: str = "success",
        error: str = "",
    ) -> None:
        self.run_id = run_id or f"mntrun_{uuid4().hex[:10]}"
        self.job_type = MaintenanceJobType(job_type) if job_type and isinstance(job_type, str) else job_type
        self.proposals_count = proposals_count
        self.started_at = started_at or datetime.now(tz=UTC).isoformat()
        self.completed_at = completed_at or datetime.now(tz=UTC).isoformat()
        self.outcome = outcome
        self.error = error

    def to_dict(self) -> dict[str, Any]:
        job_type_val = self.job_type.value if isinstance(self.job_type, MaintenanceJobType) else str(self.job_type or "")
        return {
            "run_id": self.run_id,
            "job_type": job_type_val,
            "proposals_count": self.proposals_count,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "outcome": self.outcome,
            "error": self.error,
        }


# ---------------------------------------------------------------------------
# Maintenance store (persistence for proposals and runs)
# ---------------------------------------------------------------------------


class MaintenanceStore:
    """Persist maintenance proposals and run history.

    Stored as YAML files alongside the backlog:
    - maintenance_proposals.yaml  - pending and recent proposals
    - maintenance_runs.yaml         - history of maintenance runs
    """

    def __init__(self, config: Config | None = None) -> None:
        self._proposals_path = resolve_content_gen_file_path(
            explicit_path=None,
            config=config,
            config_attr="backlog_path",
            default_name="maintenance_proposals.yaml",
            use_config_parent=True,
        )
        self._runs_path = resolve_content_gen_file_path(
            explicit_path=None,
            config=config,
            config_attr="backlog_path",
            default_name="maintenance_runs.yaml",
            use_config_parent=True,
        )
        self._proposals_path.parent.mkdir(parents=True, exist_ok=True)

    # Proposals

    def load_proposals(
        self,
        status: MaintenanceProposalStatus | None = None,
        job_type: MaintenanceJobType | None = None,
        limit: int = 100,
    ) -> list[MaintenanceProposal]:
        """Load maintenance proposals with optional filtering."""
        if not self._proposals_path.exists():
            return []

        data = yaml.safe_load(self._proposals_path.read_text()) or []
        proposals = [MaintenanceProposal.from_dict(p) for p in data]

        if status:
            proposals = [p for p in proposals if p.status == status]
        if job_type:
            proposals = [p for p in proposals if p.job_type == job_type]

        proposals.sort(key=lambda p: (p.priority, p.created_at), reverse=True)
        return proposals[:limit]

    def save_proposal(self, proposal: MaintenanceProposal) -> None:
        """Add or update a maintenance proposal."""
        data: list[dict[str, Any]] = []
        if self._proposals_path.exists():
            data = yaml.safe_load(self._proposals_path.read_text()) or []

        # Replace if same proposal_id exists, otherwise append
        replaced = False
        for i, p in enumerate(data):
            if p.get("proposal_id") == proposal.proposal_id:
                data[i] = proposal.to_dict()
                replaced = True
                break
        if not replaced:
            data.append(proposal.to_dict())

        self._proposals_path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))

    def resolve_proposal(
        self,
        proposal_id: str,
        decision: str,  # "approved" | "rejected"
        reviewed_by: str = "",
    ) -> MaintenanceProposal | None:
        """Resolve a proposal (approve or reject)."""
        if not self._proposals_path.exists():
            return None

        data: list[dict[str, Any]] = yaml.safe_load(self._proposals_path.read_text()) or []
        for p in data:
            if p.get("proposal_id") == proposal_id:
                p["status"] = (
                    MaintenanceProposalStatus.APPROVED.value
                    if decision == "approved"
                    else MaintenanceProposalStatus.REJECTED.value
                )
                p["reviewed_at"] = datetime.now(tz=UTC).isoformat()
                p["reviewed_by"] = reviewed_by
                p["outcome"] = decision
                proposal = MaintenanceProposal.from_dict(p)
                self._proposals_path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))
                return proposal
        return None

    def expire_proposal(self, proposal_id: str) -> None:
        """Mark a proposal as expired."""
        if not self._proposals_path.exists():
            return

        data: list[dict[str, Any]] = yaml.safe_load(self._proposals_path.read_text()) or []
        for p in data:
            if p.get("proposal_id") == proposal_id:
                p["status"] = MaintenanceProposalStatus.EXPIRED.value
                p["reviewed_at"] = datetime.now(tz=UTC).isoformat()
                p["outcome"] = "expired"
                break
        self._proposals_path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))

    # Runs

    def save_run(self, run: MaintenanceRun) -> None:
        """Append a maintenance run record."""
        data: list[dict[str, Any]] = []
        if self._runs_path.exists():
            data = yaml.safe_load(self._runs_path.read_text()) or []
        data.append(run.to_dict())
        # Keep last 100 runs
        if len(data) > 100:
            data = data[-100:]
        self._runs_path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))

    def load_runs(self, limit: int = 20) -> list[MaintenanceRun]:
        """Load recent maintenance run records."""
        if not self._runs_path.exists():
            return []
        data: list[dict[str, Any]] = yaml.safe_load(self._runs_path.read_text()) or []
        runs = [MaintenanceRun(**r) if isinstance(r, dict) else r for r in data]
        runs.sort(key=lambda r: r.started_at, reverse=True)
        return runs[:limit]


# ---------------------------------------------------------------------------
# Maintenance jobs (the actual analysis logic)
# ---------------------------------------------------------------------------


def _similarity(a: str, b: str) -> float:
    """Return a 0-1 similarity score between two strings."""
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


class MaintenanceJobs:
    """Collection of maintenance job analyzers.

    Each job is a method that takes the backlog items and config,
    and returns a list of MaintenanceProposal objects.
    """

    def __init__(self, config: Config | None = None) -> None:
        self._config = config
        self._backlog_service = BacklogService(config)

    # -------------------------------------------------------------------------
    # Job 1: Stale item review
    # -------------------------------------------------------------------------

    def run_stale_item_review(
        self,
        stale_days: int = 60,
        watch_days: int = 30,
    ) -> list[MaintenanceProposal]:
        """Find items not meaningfully updated in stale_days.

        Items not updated in `stale_days` are flagged for archival review.
        Items updated between `watch_days` and `stale_days` are flagged
        for enrichment (fresh look).
        """
        proposals: list[MaintenanceProposal] = []
        backlog = self._backlog_service.load()
        now = datetime.now(tz=UTC)
        stale_cutoff = now - timedelta(days=stale_days)
        watch_cutoff = now - timedelta(days=watch_days)

        for item in backlog.items:
            if item.status == "archived" or item.production_status == "ready_to_publish":
                continue

            last_updated = item.updated_at
            if not last_updated:
                last_updated = item.created_at
            if not last_updated:
                continue

            try:
                updated_dt = datetime.fromisoformat(last_updated)
                if updated_dt.tzinfo is None:
                    updated_dt = updated_dt.replace(tzinfo=UTC)
            except (ValueError, TypeError):
                continue

            if updated_dt < stale_cutoff:
                proposals.append(
                    MaintenanceProposal(
                        job_type=MaintenanceJobType.STALE_ITEM_REVIEW,
                        title=f"Stale item: {item.title or item.idea}",
                        description=(
                            f"This item has not been updated since {updated_dt.strftime('%Y-%m-%d')} "
                            f"({stale_days}+ days ago). Consider archiving it if it's no longer relevant."
                        ),
                        affected_idea_ids=[item.idea_id],
                        suggested_patch={"status": "archived"},
                        priority=3,
                    )
                )
            elif updated_dt < watch_cutoff:
                proposals.append(
                    MaintenanceProposal(
                        job_type=MaintenanceJobType.STALE_ITEM_REVIEW,
                        title=f"Needs refresh: {item.title or item.idea}",
                        description=(
                            f"This item was last updated {updated_dt.strftime('%Y-%m-%d')} "
                            f"({watch_days}-{stale_days} days ago). A fresh look or new evidence "
                            "might improve its quality."
                        ),
                        affected_idea_ids=[item.idea_id],
                        suggested_patch={},  # No auto-patch; just surface for review
                        priority=1,
                    )
                )

        return proposals

    # -------------------------------------------------------------------------
    # Job 2: Gap summary
    # -------------------------------------------------------------------------

    def run_gap_summary(self, min_items_per_theme: int = 3) -> list[MaintenanceProposal]:
        """Identify themes or categories with low coverage.

        Groups backlog items by source_theme or category and flags
        underrepresented themes for new content ideas.
        """
        proposals: list[MaintenanceProposal] = []
        backlog = self._backlog_service.load()

        # Group by theme
        theme_items: dict[str, list[BacklogItem]] = {}
        for item in backlog.items:
            if item.status == "archived" or item.production_status == "ready_to_publish":
                continue
            theme = (item.source_theme or "").strip() or "_untitled_"
            if theme not in theme_items:
                theme_items[theme] = []
            theme_items[theme].append(item)

        active_themes = {t: items for t, items in theme_items.items() if len(items) < min_items_per_theme}

        for theme, items in active_themes.items():
            if theme == "_untitled_":
                description = (
                    f"{len(items)} items have no theme assigned. "
                    "Consider grouping them under a common theme or archiving low-quality items."
                )
            else:
                description = (
                    f'Theme "{theme}" has only {len(items)} active item(s). '
                    "Consider adding more ideas before moving to production."
                )
            proposals.append(
                MaintenanceProposal(
                    job_type=MaintenanceJobType.GAP_SUMMARY,
                    title=f'Gap: under-covered theme "{theme}"',
                    description=description,
                    affected_idea_ids=[item.idea_id for item in items],
                    suggested_patch={},
                    priority=2,
                )
            )

        return proposals

    # -------------------------------------------------------------------------
    # Job 3: Duplicate watchlist
    # -------------------------------------------------------------------------

    def run_duplicate_watchlist(
        self,
        similarity_threshold: float = 0.85,
        max_items: int = 50,
    ) -> list[MaintenanceProposal]:
        """Find pairs of items with highly similar titles or ideas.

        Items above the similarity threshold are flagged as potential
        duplicates for operator deduping review.
        """
        proposals: list[MaintenanceProposal] = []
        backlog = self._backlog_service.load()

        active_items = [
            item
            for item in backlog.items
            if item.status != "archived" and item.production_status != "ready_to_publish"
        ][:max_items]

        seen_pairs: set[tuple[str, str]] = set()
        for i, a in enumerate(active_items):
            for b in active_items[i + 1 :]:
                key = (a.idea_id, b.idea_id)
                if key in seen_pairs:
                    continue

                title_sim = _similarity(a.title or "", b.title or "")
                idea_sim = _similarity(a.idea or "", b.idea or "")
                best_sim = max(title_sim, idea_sim)

                if best_sim >= similarity_threshold:
                    seen_pairs.add(key)
                    descriptions = [
                        f'Item A: "{a.title or a.idea}" (status={a.status})',
                        f'Item B: "{b.title or b.idea}" (status={b.status})',
                        f"Similarity: {best_sim:.0%}",
                    ]
                    if title_sim > idea_sim:
                        descriptions.append("(High title similarity)")
                    else:
                        descriptions.append("(High idea similarity)")

                    proposals.append(
                        MaintenanceProposal(
                            job_type=MaintenanceJobType.DUPLICATE_WATCHLIST,
                            title=f"Potential duplicate pair: {a.title or a.idea[:30]}",
                            description=" | ".join(descriptions),
                            affected_idea_ids=[a.idea_id, b.idea_id],
                            suggested_patch={},  # Operator decides which to keep
                            priority=2,
                        )
                    )

        return proposals

    # -------------------------------------------------------------------------
    # Job 4: Rescoring recommendations
    # -------------------------------------------------------------------------

    def run_rescoring_recommend(
        self,
        stale_score_days: int = 30,
    ) -> list[MaintenanceProposal]:
        """Find items with stale scores that should be re-evaluated.

        Items that have been scored but not re-scored in a long time
        are flagged for rescoring in the next pipeline run.
        """
        proposals: list[MaintenanceProposal] = []
        backlog = self._backlog_service.load()
        now = datetime.now(tz=UTC)
        stale_cutoff = now - timedelta(days=stale_score_days)

        for item in backlog.items:
            if item.status == "archived" or item.production_status != "idle":
                continue
            if not item.last_scored_at:
                continue

            try:
                scored_dt = datetime.fromisoformat(item.last_scored_at)
                if scored_dt.tzinfo is None:
                    scored_dt = scored_dt.replace(tzinfo=UTC)
            except (ValueError, TypeError):
                continue

            if scored_dt < stale_cutoff:
                proposals.append(
                    MaintenanceProposal(
                        job_type=MaintenanceJobType.RESCORING_RECOMMEND,
                        title=f"Stale score: {item.title or item.idea}",
                        description=(
                            f"This item was last scored on {scored_dt.strftime('%Y-%m-%d')} "
                            f"({stale_score_days}+ days ago). "
                            "Its scores may no longer reflect current relevance."
                        ),
                        affected_idea_ids=[item.idea_id],
                        suggested_patch={},  # Rescoring happens in pipeline; just surface for awareness
                        priority=1,
                    )
                )

        return proposals


# ---------------------------------------------------------------------------
# Maintenance scheduler
# ---------------------------------------------------------------------------


class MaintenanceScheduler:
    """In-process scheduler for recurring maintenance jobs.

    Uses a background thread with a threading.Timer loop to run
    maintenance jobs on a configurable interval.

    Jobs are read-mostly: they generate proposals surfaced to the
    operator, not direct mutations. Mutations require approval.
    """

    def __init__(
        self,
        config: Config | None = None,
        interval_hours: float = 24.0,
    ) -> None:
        self._config = config
        self._interval_hours = interval_hours
        self._timer: threading.Timer | None = None
        self._running = False
        self._lock = threading.Lock()
        self._audit_store = AuditStore(config=config)

    def start(self) -> None:
        """Start the maintenance scheduler in a background thread."""
        with self._lock:
            if self._running:
                return
            self._running = True
            self._schedule_next()

    def stop(self) -> None:
        """Stop the scheduler."""
        with self._lock:
            self._running = False
            if self._timer is not None:
                self._timer.cancel()
                self._timer = None

    def _schedule_next(self) -> None:
        """Schedule the next maintenance run."""
        interval_ms = int(self._interval_hours * 3600 * 1000)
        self._timer = threading.Timer(interval_ms / 1000, self._run_jobs)
        self._timer.daemon = True
        self._timer.start()

    def _run_jobs(self) -> None:
        """Run all maintenance jobs and reschedule."""
        if not self._running:
            return

        try:
            self.run_all_jobs()
        except Exception:
            logger.exception("Maintenance job run failed")

        if self._running:
            self._schedule_next()

    def run_all_jobs(self) -> list[MaintenanceRun]:
        """Run all maintenance jobs and persist proposals.

        Returns a list of MaintenanceRun records (one per job type).
        """
        jobs = MaintenanceJobs(self._config)
        store = MaintenanceStore(self._config)
        runs: list[MaintenanceRun] = []

        job_types = [
            MaintenanceJobType.STALE_ITEM_REVIEW,
            MaintenanceJobType.GAP_SUMMARY,
            MaintenanceJobType.DUPLICATE_WATCHLIST,
            MaintenanceJobType.RESCORING_RECOMMEND,
        ]

        for job_type in job_types:
            run = MaintenanceRun(job_type=job_type)
            try:
                if job_type == MaintenanceJobType.STALE_ITEM_REVIEW:
                    proposals = jobs.run_stale_item_review()
                elif job_type == MaintenanceJobType.GAP_SUMMARY:
                    proposals = jobs.run_gap_summary()
                elif job_type == MaintenanceJobType.DUPLICATE_WATCHLIST:
                    proposals = jobs.run_duplicate_watchlist()
                elif job_type == MaintenanceJobType.RESCORING_RECOMMEND:
                    proposals = jobs.run_rescoring_recommend()
                else:
                    proposals = []

                for proposal in proposals:
                    store.save_proposal(proposal)

                run.proposals_count = len(proposals)
                run.completed_at = datetime.now(tz=UTC).isoformat()

                # Log to audit
                self._audit_store.log_backlog_mutation(
                    event_type=AuditEventType.MAINTENANCE_JOB_RUN,
                    idea_id="",
                    actor=AuditActor.MAINTENANCE,
                    patch={"job_type": job_type.value, "proposals_count": len(proposals)},
                    outcome="success",
                )
            except Exception as exc:
                run.completed_at = datetime.now(tz=UTC).isoformat()
                run.outcome = "error"
                run.error = traceback.format_exc()
                logger.exception("Maintenance job %s failed", job_type.value)

            store.save_run(run)
            runs.append(run)

        return runs

    def trigger_job(self, job_type: MaintenanceJobType) -> MaintenanceRun:
        """Trigger a single maintenance job immediately (on-demand)."""
        jobs = MaintenanceJobs(self._config)
        store = MaintenanceStore(self._config)
        run = MaintenanceRun(job_type=job_type)

        try:
            if job_type == MaintenanceJobType.STALE_ITEM_REVIEW:
                proposals = jobs.run_stale_item_review()
            elif job_type == MaintenanceJobType.GAP_SUMMARY:
                proposals = jobs.run_gap_summary()
            elif job_type == MaintenanceJobType.DUPLICATE_WATCHLIST:
                proposals = jobs.run_duplicate_watchlist()
            elif job_type == MaintenanceJobType.RESCORING_RECOMMEND:
                proposals = jobs.run_rescoring_recommend()
            else:
                proposals = []

            for proposal in proposals:
                store.save_proposal(proposal)

            run.proposals_count = len(proposals)
            run.completed_at = datetime.now(tz=UTC).isoformat()

            self._audit_store.log_backlog_mutation(
                event_type=AuditEventType.MAINTENANCE_JOB_RUN,
                idea_id="",
                actor=AuditActor.MAINTENANCE,
                patch={"job_type": job_type.value, "proposals_count": len(proposals)},
                outcome="success",
            )
        except Exception as exc:
            run.completed_at = datetime.now(tz=UTC).isoformat()
            run.outcome = "error"
            run.error = traceback.format_exc()
            logger.exception("Maintenance job %s failed", job_type.value)

        store.save_run(run)
        return run
